### ISSUE TITLE
linqs-data.soe.ucsc.edu, maven.linqs.org not responding

### ISSUE THREAD

**Issue by eaubin** [linqs/psl-website#2]
Attempting to run the PSL tutorial, downloading `https://linqs-data.soe.ucsc.edu/maven/repositories/psl-releases/org/linqs/psl-cli/2.1.0/psl-cli-2.1.0.jar` times out. 

Building from source with `mvn install` fails when downloading `http://maven.linqs.org/maven/repositories/psl-releases/edu/emory/mathcs/parallelcolt/0.9.4/parallelcolt-0.9.4.pom`. Loading pom in a browser also times out.

**Comment by eriq-augustine** [comment]
The host went down for a bit, but should be back up now.
I'm going to close the issue, but feel free to respond if it is still down for you.
